### ISSUE TITLE
AccountHash

### ISSUE THREAD

**Issue by andrsv** [gwash/afraid-dyndns#2]
Can't get Hashmap to work(values are slightly changed to avoid abuse).

I keep getting the error-message 
anders@anders/usr/bin$ afraid-dyndns 
No AccountHash in configuration file - please see README for instructions. Done at /usr/bin/afraid-dyndns line 62.

Username: anders12345s
Password: 123simple

SHA1("anders12345s|123simple") = 391A8D6C81F7E6D2D556B3BFE3F4D927D579A9B2

/etc/afraid-dyndns.conf:
AccountHash = 391A8D6C81F7E6D2D556B3BFE3F4D927D579A9B2 
Notify = anders12345s@gmail.com
CacheFile = /var/cache/afraid-dyndns/IP

**Comment by jeremy-audet** [comment]
As outlined in the error message, this error will occur if AccountHash does not exist in the configuration file. However, that error will also occur if the configuration file is either non-existent or cannot be read. I just tested such myself.

Try adding this code at line 58:
die("Configuration file either does not exist or cannot be read.\n") unless(&readfile($CONF));

**Comment by andrsv** [comment]
Thanks!

That is very plausible. Today my computer wouldn't boot as it could not mount parts of my disc.

I'll test it if i manage to boot my computer.

**Comment by andrsv** [comment]
Thanks,

it seems I had the wrong version of the program, I downloaded by instructions from http://freedns.afraid.org/scripts/freedns.clients.php.

Problem solved after updating to latest version.

**Comment by Momus** [comment]
Just FYI, I encountered this problem when installing from the Fedora Core repositories.   Installing this version fixed it.  Bug filed with the Red Hat's Bugzilla.
